name: Build Unity Project and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "release-*"

permissions:
  contents: write

jobs:
  # 先に tag_name を決めるジョブ
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.outputs.tag_name }}
    steps:
      - name: Determine tag name
        id: tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "tag_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=build-${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    needs: prepare
    strategy: 
      matrix: 
        include: 
          - targetPlatform: StandaloneWindows64 
            osName: windows 
          - targetPlatform: StandaloneOSX 
            osName: macos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ github.sha }}

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 6000.0.26f1
          buildName: MWSQuestII_${{ matrix.osName }}_${{ needs.prepare.outputs.tag_name }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MWSQuestII_${{ matrix.osName }}_${{ needs.prepare.outputs.tag_name }}
          path: build/${{ matrix.targetPlatform }}

  release:
    runs-on: ubuntu-latest
    needs: [prepare, build]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: builds

      - name: Zip builds
        run: |
          cd builds
          for dir in *; do
            zip -r "${dir}.zip" "$dir"
          done
      
      - name: Create Release with Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare.outputs.tag_name }}
          name: Unity Build ${{ github.run_number }}
          body: |
            This release contains the latest Unity builds.
          files: builds/*.zip
